openebs/mayastor-control-plane

Cargo.lock
Cargo.toml
control-plane/deployer/Cargo.toml
control-plane/deployer/src/infra/etcd.rs
control-plane/deployer/src/infra/mod.rs
control-plane/deployer/src/lib.rs
control-plane/store/Cargo.toml
control-plane/store/README.md
control-plane/store/src/etcd.rs
control-plane/store/src/kv_store.rs
control-plane/store/src/lib.rs
control-plane/store/tests/etcd.rs
shell.nix

Include support for a key-value store which can be used by the control
plane to persist information.
etcd has been selected as the key-value store to use.
Add deployer support for etcd. To launch etcd include the '--etcd'
argument.
Resolves: CAS-765

feat(persistent store): add a key-value store

---

control-plane/agents/common/src/errors.rs
control-plane/agents/core/src/volume/service.rs

Support for ANA is not yet implemented, however it is possible when
creating a volume to specify multiple nexuses. Rather than panicking
when this occurs, return an appropriate error.

refactor(remove panic): return error for ANA

---

Cargo.lock
control-plane/macros/actix/src/lib.rs
control-plane/rest/service/src/v0/block_devices.rs
control-plane/rest/service/src/v0/children.rs
control-plane/rest/service/src/v0/jsongrpc.rs
control-plane/rest/service/src/v0/mod.rs
control-plane/rest/service/src/v0/nexuses.rs
control-plane/rest/service/src/v0/nodes.rs
control-plane/rest/service/src/v0/pools.rs
control-plane/rest/service/src/v0/replicas.rs
control-plane/rest/service/src/v0/volumes.rs
control-plane/rest/src/versions/v0.rs
nix/pkgs/control-plane/cargo-project.nix

- refactor(rest): simplify the openapi macros
Simplify the openapi macros which at the moment have the full and relative
path for a handler. This is possible thanks to the paperclip change which
trims the base path of all handlers if it matches the api base path.
This means we can now use scopes to avoid repeating the base path on each
handler's macro.
- fix(errors): map actix builtin errors
The Path and Json body validation are handle by the actix; in case of
error we should make it to our own error types.
Now that we have scopes we can easily add an error to the v0 scope.
Example of Invalid JSON bodies error:
400: Bad Request
{
"error": "Deserialize",
"details": "Json deserialize error: missing field `size` at line 4 column 1"
}

fix: map actix builtin errors to our control plane errors

---

control-plane/mbus-api/src/message_bus/v0.rs

The only_one macro was not using the provided filter as a means of
finding an item in a list; it was only being recorded in the error
messages.

chore(filter): remove filter from only_one macro

---

Cargo.toml
nix/overlay.nix

Update mayastor to 2868e83704177e439d7bfb4cbd94cff5a371db91 (current
tip of develop branch)
This should get rid of the nix-build issues with the sha256.

chore: update mayastor

---

Cargo.lock
control-plane/agents/core/src/watcher/watch.rs
control-plane/store/src/etcd.rs
control-plane/store/src/store.rs

Remove the unneeded lifetime bounds on the StorableObject.
The 'Deserialize' trait with the 'Higher Rank Trait Bounds' has been
replaced with the 'DeserializeOwned' trait which is equivalent (see the
"Trait bounds" section of https://serde.rs/lifetimes.html).

chore(lifetimes): simplify store lifetimes

---

tests-mayastor/tests/nexus.rs

The Jira item referenced for this test case has been marked as resolved
so the expectation is that this test case should now pass.

chore: remove "allow fail" for test case

---

control-plane/agents/core/src/node/service.rs
control-plane/agents/core/src/pool/specs.rs

Include the list of pools when getting the specs from the REST API.

chore: include pools when getting specs

---

common/src/mbus_api/message_bus/v0.rs
common/src/mbus_api/v0.rs
common/src/types/v0/message_bus/mod.rs
common/src/types/v0/message_bus/nexus.rs
common/src/types/v0/message_bus/pool.rs
common/src/types/v0/message_bus/replica.rs
common/src/types/v0/message_bus/state.rs
common/src/types/v0/store/nexus.rs
common/src/types/v0/store/node.rs
common/src/types/v0/store/pool.rs
common/src/types/v0/store/replica.rs
control-plane/agents/core/src/core/mod.rs
control-plane/agents/core/src/core/registry.rs
control-plane/agents/core/src/core/states.rs
control-plane/agents/core/src/core/wrapper.rs
control-plane/agents/core/src/node/mod.rs
control-plane/agents/core/src/node/service.rs
control-plane/rest/service/src/v0/mod.rs
control-plane/rest/service/src/v0/states.rs
control-plane/rest/src/versions/v0.rs

Allow the runtime states of the various resources to be exposed through
the REST API. The runtime state is updated periodically by querying the
various Mayastor instances through gRPC calls.
Note: Runtime node information is not currently supported.

feat: expose resource states through REST API

---

.gitignore
Cargo.lock
common/src/lib.rs
common/src/types/v0/message_bus/mod.rs
common/src/types/v0/message_bus/nexus.rs
common/src/types/v0/message_bus/pool.rs
common/src/types/v0/message_bus/replica.rs
common/src/types/v0/store/definitions.rs
common/src/types/v0/store/mod.rs
common/src/types/v0/store/nexus.rs
common/src/types/v0/store/node.rs
common/src/types/v0/store/pool.rs
common/src/types/v0/store/replica.rs
common/src/types/v0/store/volume.rs
control-plane/agents/Cargo.toml
control-plane/agents/core/src/core/mod.rs
control-plane/agents/core/src/core/resource_map.rs
control-plane/agents/core/src/core/specs.rs
control-plane/agents/core/src/core/states.rs
control-plane/agents/core/src/core/wrapper.rs
control-plane/agents/core/src/nexus/specs.rs
control-plane/agents/core/src/node/service.rs
control-plane/agents/core/src/pool/specs.rs
control-plane/agents/core/src/volume/registry.rs
control-plane/agents/core/src/volume/specs.rs

The ResourceSpecs and ResourceMaps have been made generic through the
use of a ResourceMap. This simplifies the interactions with these
resources.
As part of this change, the ResourceSpecs no longer require the use of
an async mutex. Instead, a sync mutex is used.
Resolves: CAS-1010

refactor: use generic ResourceMap

---

control-plane/agents/core/src/core/registry.rs
control-plane/agents/core/src/core/resource_map.rs
control-plane/agents/core/src/core/states.rs
control-plane/agents/core/src/core/wrapper.rs
control-plane/agents/core/src/nexus/specs.rs
control-plane/agents/core/src/pool/registry.rs
control-plane/agents/core/src/pool/service.rs
control-plane/agents/core/src/pool/specs.rs
control-plane/agents/core/src/volume/specs.rs
control-plane/rest/tests/v0_test.rs

The NodeWrapper now uses the ResourceStatesLocked structure to maintain
runtime information from Mayastor. The removes the need for the
NodeWrapper to maintain a separate pools and nexuses hashmap.
Resolves: CAS-985

refactor(NodeWrapper): use ResourceStatesLocked

---

control-plane/agents/core/src/core/registry.rs
control-plane/agents/core/src/core/wrapper.rs
control-plane/agents/core/src/node/service.rs

The state information for resources are store per node in the
NodeWrapper, therefore remove the states from the registry as this is no
longer needed.

chore: remove states from registry

---

common/src/types/v0/message_bus/child.rs
common/src/types/v0/message_bus/replica.rs
common/src/types/v0/store/definitions.rs
common/src/types/v0/store/mod.rs
common/src/types/v0/store/nexus_persistence.rs
common/src/types/v0/store/volume.rs
control-plane/agents/common/src/errors.rs
control-plane/agents/core/src/core/registry.rs
control-plane/agents/core/src/core/scheduling/mod.rs
control-plane/agents/core/src/core/scheduling/nexus.rs
control-plane/agents/core/src/core/scheduling/resources/mod.rs
control-plane/agents/core/src/core/scheduling/volume.rs
control-plane/agents/core/src/core/tests.rs
control-plane/agents/core/src/nexus/registry.rs
control-plane/agents/core/src/nexus/specs.rs
control-plane/agents/core/src/nexus/tests.rs
control-plane/agents/core/src/node/service.rs
control-plane/agents/core/src/pool/registry.rs
control-plane/agents/core/src/pool/service.rs
control-plane/agents/core/src/pool/specs.rs
control-plane/agents/core/src/volume/scheduling.rs
control-plane/agents/core/src/volume/specs.rs
control-plane/agents/core/src/volume/tests.rs
deployer/src/infra/mayastor.rs
tests-mayastor/tests/nexus.rs

When mayastor nexus faults a child it updates its persistent nexus information on etcd to
mark the child as not healthy.
Also when the nexus is not shutdown cleanly, then the clean flag remains unset on etcd.
The control plane now inspects this information on etcd before attempting to create a nexus.
It selects a list of replicas for nexus creation and filters them down according to the
information it retrieved from etcd.
Added tests for various cases where replicas are faulted. These faults are mocked.
Change node_wrapper getter to return an error if the node cannot be found.
Fix tests to use uuid as a query parameter when creating a nexus.

fix: create nexuses with only healthy replicas

---

common/src/types/v0/message_bus/pool.rs
common/src/types/v0/message_bus/replica.rs
common/src/types/v0/store/mod.rs
common/src/types/v0/store/nexus.rs
common/src/types/v0/store/pool.rs
common/src/types/v0/store/replica.rs
common/src/types/v0/store/volume.rs
control-plane/agents/common/src/v0/msg_translation.rs
control-plane/agents/core/src/core/mod.rs
control-plane/agents/core/src/core/reconciler/mod.rs
control-plane/agents/core/src/core/reconciler/persistent_store.rs
control-plane/agents/core/src/core/reconciler/poller.rs
control-plane/agents/core/src/core/reconciler/volume/garbage_collector.rs
control-plane/agents/core/src/core/reconciler/volume/hot_spare.rs
control-plane/agents/core/src/core/reconciler/volume/mod.rs
control-plane/agents/core/src/core/registry.rs
control-plane/agents/core/src/core/scheduling/mod.rs
control-plane/agents/core/src/core/specs.rs
control-plane/agents/core/src/core/task_poller.rs
control-plane/agents/core/src/core/wrapper.rs
control-plane/agents/core/src/nexus/specs.rs
control-plane/agents/core/src/pool/specs.rs
control-plane/agents/core/src/pool/tests.rs
control-plane/agents/core/src/server.rs
control-plane/agents/core/src/volume/specs.rs

chore: correct remaining state/status naming
feat: add initial reconciliation task scaffolding
Add reconciliation pollers that get polled at a certain interval. Each poller may then mux
Added example volume pollers for replica hotspare and garbage collection.
refactor: update old dirty specs reconciler
Use the new reconciler poller to reconcile dirty specs into the persistent store

feat: initial reconciliation scaffolding

---

common/src/mbus_api/mod.rs
common/src/types/mod.rs
control-plane/agents/common/src/errors.rs
control-plane/agents/core/src/pool/tests.rs
control-plane/rest/openapi-specs/v0_api_spec.yaml
openapi/api/openapi.yaml
openapi/src/models/rest_json_error.rs

Return an InUse error message when attempting to delete a pool which has
replicas on it.
Resolves: CAS-996

chore: add InUse error when deleting a pool

---

Cargo.lock
common/src/types/v0/store/mod.rs
common/src/types/v0/store/nexus.rs
common/src/types/v0/store/volume.rs
control-plane/agents/Cargo.toml
control-plane/agents/common/src/errors.rs
control-plane/agents/core/src/core/reconciler/nexus/mod.rs
control-plane/agents/core/src/core/reconciler/poller.rs
control-plane/agents/core/src/core/reconciler/volume/hot_spare.rs
control-plane/agents/core/src/core/scheduling/mod.rs
control-plane/agents/core/src/core/scheduling/nexus.rs
control-plane/agents/core/src/core/scheduling/resources/mod.rs
control-plane/agents/core/src/core/scheduling/volume.rs
control-plane/agents/core/src/core/specs.rs
control-plane/agents/core/src/core/task_poller.rs
control-plane/agents/core/src/nexus/registry.rs
control-plane/agents/core/src/nexus/service.rs
control-plane/agents/core/src/nexus/specs.rs
control-plane/agents/core/src/pool/service.rs
control-plane/agents/core/src/pool/specs.rs
control-plane/agents/core/src/server.rs
control-plane/agents/core/src/volume/scheduling.rs
control-plane/agents/core/src/volume/service.rs
control-plane/agents/core/src/volume/specs.rs
control-plane/agents/core/src/volume/tests.rs
control-plane/rest/Cargo.toml
control-plane/rest/tests/v0_test.rs
deployer/src/infra/mod.rs
deployer/src/infra/rest.rs
tests-mayastor/Cargo.toml

fix: don't remove too many replicas
When removing a replica from a volume or a child from a nexus we could
potentially "too many" and cause the volume to become degraded, or worst, faulted.
Now, when we remove a replica we always check that we're not falling into that case.
Note: we can still get things wrong because the state of nexuses and its children
is volatile so our decisions could be based on stale information.
To address this better we need cas -1018.
feat: improve tracing of volumes, nexus and operations
Don't add a span to the main poller fn otherwise we'll have an infinite span...
Tag every reconcile top level fn and every service function with the volume/nexus id.
Add a request.type = "service|reconcile" which is useful for tracing.
Add TraceStrLog trait which allows us to …

feat: improve tracing of volumes, nexus and operations

---

tests/bdd/setup.sh

Fixup the shell script used to configure the pytest environment.

chore: fixup setup.sh

---

Jenkinsfile
shell.nix

The current agent 'nixos-mayastor-pytest' is no longer available
as the node upon which it resides is being repurposed
as a "hypervisor" node

chore: run bdd tests no longer run on separate agent

---

control-plane/agents/core/src/core/registry.rs
control-plane/agents/core/src/core/specs.rs
control-plane/agents/core/src/volume/specs.rs
tests/bdd/test_volume_create.py

Ensure that the volume spec is eventually deleted when volume creation
fails.
In the event that the persistent store cannot be reached, the
reconcile_dirty_volumes function will ensure that the spec will
eventually be removed from the store and registry.
Bug fix:
- Ensure that an error is returned when storing an object to the
persistent store fails.
Resolves: CAS-1059

feat: delete spec when volume creation fails

---

Jenkinsfile
control-plane/agents/core/src/core/registry.rs
deploy/core-agents-deployment.yaml
deploy/rest-deployment.yaml
deploy/rest-service.yaml
nix/pkgs/images/default.nix
scripts/release.sh

Enable CI to build and push control plane images for certain branches.
Build core and jsongrpc images separately to allow both to be loaded
from the resulting tar file. Attempting to build them both together was
resulting in only the core image being loaded from the tar file.
Provide deployment YAML files for the core agent and REST server. The
REST server is exposed through a NodePort service on port 30010.
Bug fix:
- Allow the etcd enpoint to be provided to the core agent without
the need for a port to be specified. Omitting the port results in the
default port being chosen (2379). This mimicks the behaviour of
Mayastor.
Resolves: CAS-636

feat(CI): build and push control plane images

---

common/src/types/v0/message_bus/volume.rs
common/src/types/v0/store/volume.rs
composer/src/lib.rs
control-plane/agents/common/src/errors.rs
control-plane/agents/core/src/core/grpc.rs
control-plane/agents/core/src/core/reconciler/volume/hot_spare.rs
control-plane/agents/core/src/core/scheduling/resources/mod.rs
control-plane/agents/core/src/core/scheduling/volume.rs
control-plane/agents/core/src/server.rs
control-plane/agents/core/src/volume/registry.rs
control-plane/agents/core/src/volume/specs.rs
control-plane/agents/core/src/volume/tests.rs
control-plane/rest/openapi-specs/v0_api_spec.yaml
control-plane/rest/tests/v0_test.rs
deployer/README.md
deployer/src/infra/mayastor.rs
deployer/src/lib.rs
openapi/docs/models/VolumeSpec.md
openapi/docs/models/VolumeState.md
openapi/src/models/volume_spec.rs
openapi/src/models/volume_spec_operation.rs
openapi/src/models/volume_state.rs
shell.nix
tests/bdd/test_volume_create.py
tests/bdd/test_volume_observability.py
tests/bdd/test_volume_publish.py
tests/bdd/test_volume_replicas.py
tests/bdd/test_volume_unpublish.py

chore: remove "ANA bits" from the current volume
A non-ANA volume is only meant to have one active nexus target at a time.
ANA adds a lot more complexity than than just a vector of nexuses, so it's better
to completely ignore multi volume nexuses for now and add it back later as a new
type of volume.
This way we can also make sure that we don't break non-ANA volumes when we start
adding ANA volumes..
--
chore: update the deployer docs and add block devices
Updates the readme.md to match the latest.
Add new option to add a host block device to the mayastor containers.

chore: remove ana bits from existing non-ana volumes

---

Cargo.lock
control-plane/rest/Cargo.toml
control-plane/rest/service/src/main.rs
deploy/rest-deployment.yaml

Provide a command line argument which can be used to set the timeout
time for every REST request.

feat(REST timeout): add command line argument

---

common/src/mbus_api/mod.rs
common/src/types/mod.rs
control-plane/agents/common/src/errors.rs
control-plane/agents/core/src/core/registry.rs
control-plane/agents/core/src/core/specs.rs
control-plane/agents/core/src/volume/specs.rs
tests/bdd/common.py
tests/bdd/features/volume/create.feature
tests/bdd/test_volume_create.py

Ensure the correct key is used when attempting to delete an entry from
the persistent store.
Add a BDD test to check that when a gRPC timeout occurs, associated
specs are correctly deleted from the persistent store.
Resolves: CAS-1103

fix: use correct key when deleting from store

---

kubectl-plugin/src/main.rs
nix/pkgs/control-plane/cargo-project.nix

When building the control plane ensure that the kubectl plugin is also
built.

fix: include kubectl-plugin in control plane build

---

Cargo.lock
common/src/lib.rs
common/src/types/v0/message_bus/replica.rs
common/src/types/v0/store/replica.rs
composer/src/lib.rs
control-plane/agents/common/src/errors.rs
control-plane/agents/common/src/lib.rs
control-plane/agents/common/src/v0/msg_translation.rs
control-plane/agents/core/src/core/specs.rs
control-plane/agents/core/src/core/wrapper.rs
control-plane/agents/core/src/nexus/tests.rs
control-plane/agents/core/src/pool/tests.rs
control-plane/agents/core/src/volume/specs.rs
control-plane/agents/core/src/volume/tests.rs
control-plane/rest/service/src/v0/replicas.rs
control-plane/rest/src/versions/v0.rs
control-plane/rest/tests/v0_test.rs
deployer/src/infra/mayastor.rs
deployer/src/lib.rs
kubectl-plugin/Cargo.toml
nix/overlay.nix
shell.nix
tests/tests-mayastor/Cargo.toml
tests/tests-mayastor/src/lib.rs
tests/tests-mayastor/tests/nexus.rs
tests/tests-mayastor/tests/replicas.rs

chore: use the latest mayastor
------
chore: use the replica v2 operations
Use the replica v2 operations. Replicas now carry a name and a uuid.
Set the name to "mayastor-cp-$replicaId-$volumeId". This could even let us
determine whether a replica is created by us or not and get some more info.
The Share/Unshare/Destroy were noted not to have been updated to V2:
Raised cas-1107 to address this. Meanwhile simply set None for every
request and it gets "hardcoded" to be the same as the uuid.

chore: use the replica v2 operations

---

kubectl-plugin/README.md
kubectl-plugin/src/resources/pool.rs
kubectl-plugin/src/resources/utils.rs
kubectl-plugin/src/resources/volume.rs

- This PR handles the cases when a pool is likely having its state as empty.
- This PR adds a field `MANAGED` to denote whether a pool is created by Control plane or not.

fix(kubectl-mayastor): handle cases with empty state for volume and pools, add managed field

---

deploy/terraform/main.tf
deploy/terraform/mod/core/main.tf
deploy/terraform/mod/csi-agent/main.tf
deploy/terraform/mod/csi-controller/main.tf
deploy/terraform/mod/etcd/main.tf
deploy/terraform/mod/k8s-operator/main.tf
deploy/terraform/mod/mayastor/main.tf
deploy/terraform/mod/nats/main.tf
deploy/terraform/mod/rest/main.tf
deploy/terraform/simple.tfvars
deploy/terraform/variables.tf

chore: add variables and example file for less powered vms
Add variables to modify the hugepages, cpu, cpu mask, resource requests and
resource limits and request timeouts and poll periods.
----
chore(tf): deploy the csi-controller with terraform
---
chore: match up nats and etcd probe configs

chore(tf): deploy the csi-controller with terraform

---

kubectl-plugin/src/resources/pool.rs
kubectl-plugin/src/resources/utils.rs
kubectl-plugin/src/resources/volume.rs

- Previously to reuse the code, the get and list methods were returning a json array, which is not the correct type for get.
- This fix will identify each api call and return it corresponding format.

fix(kubectl-mayastor): return single element on get volumes or pools json or yaml output

---

chart/templates/csi-deployment.yaml
deploy/csi-deployment.yaml

Add missing image pull secret for the CSI deployment.
Remove the "log-level" argument to bring the template in line with
the change to the deployment file in commit 75fa3c3e2a5c458b824fa1beef8e7959626e7a6e

fix(csi deployment): add image pull secret

---

common/src/constants.rs
common/src/types/v0/message_bus/pool.rs
common/src/types/v0/store/pool.rs
control-plane/agents/core/src/core/reconciler/pool/mod.rs
control-plane/agents/core/src/pool/tests.rs
control-plane/agents/examples/pool-client/main.rs
control-plane/msp-operator/src/main.rs
control-plane/rest/openapi-specs/v0_api_spec.yaml
control-plane/rest/src/versions/v0.rs
control-plane/rest/tests/v0_test.rs
openapi/docs/models/CreatePoolBody.md
openapi/docs/models/PoolSpec.md
openapi/src/models/create_pool_body.rs
openapi/src/models/pool_spec.rs
tests/tests-mayastor/src/lib.rs
tests/tests-mayastor/tests/pools.rs

- This PR changes the labels type to hashmap
- This adds changes to populate labels on request.
- This add changes in msp-operator, to add a unique label is the pool creation request comes to rest from msp-operator.
Signed-off-by: Abhinandan-Purkait <abhinandan.purkait@mayadata.io>

feat(pool-labels): add a unique label to all pools created by control plane on request from msp

---

kubectl-plugin/README.md
kubectl-plugin/src/main.rs
kubectl-plugin/src/resources/mod.rs
kubectl-plugin/src/resources/node.rs
kubectl-plugin/src/resources/utils.rs

- This PR adds the feature in kubectl-mayastor to list and get mayastor nodes.

feat(kubectl-mayastor): add support for listing mayastor nodes using plugin

---

Cargo.lock
composer/src/lib.rs
deploy/terraform/mod/jaeger/main.tf
kubectl-plugin/Cargo.toml
kubectl-plugin/README.md
kubectl-plugin/src/resources/utils.rs
kubectl-plugin/src/resources/volume.rs

fix(terraform): jaegertracing sometimes fails
fix(plugin): remove protocol from volume
fix(kubectl-plugin): add target-node and accessibility
Add new target-node and accessibility columns to the volume's tabular output
Added a new EMPTY_FIELD (<none>) to signify that there's nothing to output.

fix: jaegertracing sometimes fails and kubectl-plugin volume

---

tests/bdd/features/volume/topology.feature
tests/bdd/test_volume_topology.py

Add bdd tests to test the volume topology based scheduling of replicas on pools
Resolves: CAS-1156 and CAS-1116
Signed-off-by: Abhinandan-Purkait <abhinandan.purkait@mayadata.io>

test(replica scheduling): add bdd tests for volume topology based replica scheduling

---

control-plane/agents/core/src/nexus/specs.rs
control-plane/agents/core/src/volume/specs.rs

When removing a nexus child we try to destroy the underlying replica.
However, we were always issuing the destroy call to the node with the
nexus. This change ensures that the destroy call is issued to the node
that actually hosts the replica.
Resolves: CAS-1167

fix(replica destruction): issue to correct node

---

common/src/types/v0/message_bus/replica.rs
common/src/types/v0/store/nexus.rs
control-plane/agents/core/src/core/reconciler/nexus/garbage_collector.rs
control-plane/agents/core/src/core/reconciler/nexus/mod.rs
control-plane/agents/core/src/core/reconciler/pool/mod.rs
control-plane/agents/core/src/core/reconciler/volume/garbage_collector.rs
control-plane/agents/core/src/core/reconciler/volume/hot_spare.rs
control-plane/agents/core/src/volume/registry.rs
control-plane/agents/core/src/volume/specs.rs
control-plane/agents/core/src/volume/tests.rs
deployer/src/infra/csi.rs
deployer/src/lib.rs
tests/bdd/common.py
tests/bdd/test_csi_controller.py

feat(nexus): add garbage collector
Nexuses which belong to a volume which no longer exists are disowned
Nexuses which are no longer used by a volume are disowned
Nexuses with no owner are deleted
--------
fix(replica): disown unused replicas
When a volume is published with offline replicas they are not used by the
nexus. In this case we should disown these replicas since we'll have to
do a full rebuild anyway.
Disowned replicas will then garbage collected when they reappear.
--------
chore(deployer): make the csi deployment optional
The csi is not usually needed when we use the deployer so disable it by default.
It has been explicitly enabled in the bdd tests.
--------
test: add volume garbage collection cargo tests

feat(volume): add volume nexus/replica garbage collector

---

common/src/types/v0/message_bus/replica.rs
control-plane/agents/core/src/core/specs.rs
control-plane/agents/core/src/nexus/specs.rs
control-plane/agents/core/src/pool/specs.rs
control-plane/agents/core/src/volume/specs.rs
tests/bdd/features/volume/delete.feature
tests/bdd/test_volume_delete.py

Volume destruction will now complete successfully even if a node with a
replica or nexus on it is offline. In the event that the node is
inaccessible the volume resources (replicas and nexus) are completely
disowned allowing them to be garbage collected at a later time.
Resolves: CAS-1180

fix: allow volume destruction whilst node offline

---

control-plane/msp-operator/src/main.rs

The pool events now show up on the pool when you do:
kubectl -n mayastor describe msp xxx

fix(msp): use the correct pool id for events

---

Cargo.lock
Cargo.toml
common/Cargo.toml
common/src/mbus_api/mbus_nats.rs
common/src/mbus_api/mod.rs
control-plane/agents/Cargo.toml
deployer/Cargo.toml
nix/pkgs/control-plane/cargo-project.nix
nix/sources.json

chore(nats): use the nats with a stuck tcp stream fix
The tcp stream to the nats-server can get stuck if the server is not
shutdown gracefully. Even the connection lost callback does not get
triggered because the stream is somehow stuck.
----------------
fix(nats): set tcp read timeouts
The tcp stream to the nats-server can get stuck if the server is not
shutdown gracefully. As such Even the connection lost callback does not get
triggered because the stream is somehow stuck.
Adding the timeout if we do not receive a message with a timeout helps
address the issue: when the timeout expires the client now sends a ping
to the server and expects to receive a pong within the same timeout.
If a pong does not arrive in time then the connection is deemed lost.
As a side effect this may cause …

fix(nats): set tcp read timeouts

---

control-plane/agents/core/src/core/reconciler/pool/mod.rs
control-plane/agents/core/src/pool/tests.rs

- Add pool reconciler to clean up pools struck in Deleting state.
- Add tests for the same.
- Resolves [CAS-1206](https://mayadata.atlassian.net/browse/CAS-1206)

fix(pool-recreation): add pool reconciler to clean deleting pools and tests

---

common/src/constants.rs
common/src/types/v0/message_bus/nexus.rs
common/src/types/v0/store/nexus.rs
control-plane/agents/common/src/v0/msg_translation.rs
control-plane/agents/core/src/core/wrapper.rs
control-plane/agents/core/src/nexus/tests.rs
deploy/terraform/mod/csi-agent/main.tf
deployer/src/lib.rs
shell.nix

This allows the control plane to create a nexus with a name and a uuid.
The name is set to the k8s volume uuid. This is required, otherwise the
csi node plugin cannot attach/detach the nexus properly.
Note: ignored the test "nexus_share_transaction_store" as the latest
mayastor now updates etcd so the test can no longer pause etcd as it is
as it blocks mayastor. TODO: fixme

fix(nexus_v2): use nexus create v2 api

---

Cargo.lock
common/Cargo.toml
common/src/types/v0/message_bus/nexus.rs
common/src/types/v0/store/nexus.rs
control-plane/agents/common/src/v0/msg_translation.rs
control-plane/agents/core/src/volume/specs.rs
control-plane/agents/core/src/volume/tests.rs
control-plane/rest/src/versions/v0.rs
deployer/src/infra/mayastor.rs
deployer/src/infra/mod.rs
deployer/src/lib.rs
shell.nix
tests/bdd/features/ana/validate-nexus-swap.feature
tests/bdd/test_ana_validate_nexus_swap.py

test(core): add env variable to setup random min ctrl id
Tidy up the nexus nvmf config a bit.
If the env var "TEST_NEXUS_NVMF_ANA_ENABLE" is set then the min controller
will be randomly generated.
NODE: This is only useful for the ana swap test as there is no other way
of influencing this.
----------------
test(bdd): add ana swap test
This tests the ana swap by:
1. enabling ana
2. publishing a volume to an ana host
3. running fio
4. killing the volume target (nexus)
5. republish the volume on another mayastor
6. connect to the new target
7. remove the old target
8. fio completes with no errors

test(bdd): add ana swap test

---

common/src/types/v0/store/nexus_persistence.rs
control-plane/agents/core/src/core/reconciler/nexus/garbage_collector.rs
control-plane/agents/core/src/core/reconciler/poller.rs
control-plane/agents/core/src/core/reconciler/replica/mod.rs
control-plane/agents/core/src/core/reconciler/volume/garbage_collector.rs
control-plane/agents/core/src/core/task_poller.rs

When the nexus is not in the created phase don't disown replicas, wait
until the nexus is created so that we have a clear picture of what's
unused.
Also, make sure we don't disown healthy replicas.

fix(bug): don't disown unused replicas

---

control-plane/csi-controller/src/client.rs
control-plane/csi-controller/src/controller.rs
tests/bdd/features/csi/controller.feature
tests/bdd/test_csi_controller.py

ControllerUnpublishVolume() now successfully unpublishes the volumes
whose nexuses are located on offline nodes.
Resolves: CAS-1236

fix(csi): fixed volume unpublishing for offlined nexuses

---

control-plane/agents/core/src/pool/registry.rs
control-plane/msp-operator/src/main.rs

Fix for the bug which causes the CR status to go from CREATING to ERROR.
Added checks to handle PRECONDITION_FAILED errors.
Resolves [CAS-1244](https://mayadata.atlassian.net/browse/CAS-1244)

fix(msp cr status): add fix for msp cr going to error state on node down

---

control-plane/agents/core/src/core/reconciler/volume/hot_spare.rs
control-plane/agents/core/src/volume/specs.rs
control-plane/agents/core/src/volume/tests.rs

When >1 replicas fail at the same time, the core agent was running the
scheduling algorithm once and then using the result to create new replicas.
The fix is to run the scheduling algorithm for each new replica we're adding.
This way we always make sure that we respect the scheduling rules.

fix(hotspare): schedule replicas individually

---

control-plane/agents/common/src/errors.rs
control-plane/agents/core/src/volume/specs.rs
tests/bdd/common/docker.py
tests/bdd/features/volume/replicas.feature
tests/bdd/test_volume_replicas.py

When decrementing the number of volume replicas, it is possible that the
runtime number of replicas already matches the desired number of
replicas. In this case no replica removal candidates will be identified
and the operation can simply be completed successfully (ensuring the
persistent store is updated).
Resolves: CAS-1251

fix(replica): decrementing volume replica count

---

nix/pkgs/control-plane/cargo-project.nix
nix/pkgs/utils/default.nix

Allow control plane images to be built using the composer that has been
moved to a different repo.

fix(build images): composer repo

---

Cargo.lock
control-plane/msp-operator/Cargo.toml
default.nix
nix/lib/rust.nix
nix/lib/version.nix
nix/overlay.nix
nix/pkgs/control-plane/cargo-project.nix
nix/pkgs/control-plane/default.nix
nix/pkgs/images/default.nix
nix/pkgs/openapi-generator/default.nix
nix/sources.json
nix/sources.nix
rpc/src/lib.rs
scripts/release.sh
shell.nix
tests/bdd/features/garbage-collection/replicas/test_feature.py

chore(nix): format the existing nix files with nixpkgs-fmt
---------
refactor(images): tidy up building of images
There's a new build type at the root of the images which should simplify
adding new images (no need for -dev or -cov). Example, to build a debug
version of the core agent:
nix-build -A images.debug.agents.core
Add a build suffix to fix the debug builds which are broken. Example:
the core agent image will be named mcp-core and the debug mcp-core-dev
---------
chore(build): add allInOne and incremental arguments to the nix build
With allInOne set to true all components are built as part of the same "cargo build" derivation
this allows for a quicker build of all components but slower single components
with allInOne set to false each compoment gets its own "cargo build" derivation …

refactor(images): fix debug images and allow for faster incremental builds

---

.vscode/settings.json
control-plane/agents/core/src/core/grpc.rs
control-plane/agents/core/src/core/reconciler/nexus/mod.rs
control-plane/agents/core/src/core/reconciler/pool/mod.rs
control-plane/agents/core/src/core/registry.rs
control-plane/agents/core/src/core/wrapper.rs
control-plane/agents/core/src/node/service.rs
control-plane/agents/core/src/pool/specs.rs
control-plane/agents/core/src/volume/specs.rs
control-plane/rest/tests/v0_test.rs
nix/lib/rust.nix
shell.nix

Instead of using a copy of the node to reload, use the node itself with a grpc locked client to
update the nodes when the registry is polling mayastor.
Extra:
To clarity, in the client operations, pass the grpc client down to the update operations to that its
use is explicit rather than implicit. Added a TODO to allow us to use different timeouts for the
list operations without having to reconnect the gRPC client.
Use more getters rather than accessing fields directly

fix(node): node status overridden with stale status

---

deploy/core-agents-deployment.yaml
deploy/csi-deployment.yaml
deploy/msp-deployment.yaml
deploy/rest-deployment.yaml

Update k8s definition files referenced in the user
docs as an example deployment
- Container image tags should reflect 1.0.0 release version
- Template used should be the 'Release' profile

chore: update example deployment definition files

---

nix/pkgs/control-plane/cargo-project.nix
nix/pkgs/utils/default.nix
shell.nix

fix: update nix derivations
Add new utils folder to the src derivation.
Remove debug breakpoint that should not have been left in the code.
--------------
chore: add cargo-expand to the nix-shell

fix: update nix derivations

---

common/src/types/v0/message_bus/volume.rs
control-plane/agents/core/src/volume/tests.rs

CI occasionally shows the "hotspare" test failing; specifically in the
"hotspare_replica_count_spread" function.
The problem appears to be in the "wait_till_volume" function where we
were waiting for the number of replicas to be correct. However, we were
checking the replica count in the spec, which defines the desired number
of replicas rather than the actual number of replicas in the system.
This function has been enhanced to check the replica topology field in
the volume state which will give the number of actual replicas.

fix(rust test): fix occasional CI test failures

---

Cargo.lock
tests/tests-mayastor/Cargo.toml
tests/tests-mayastor/src/lib.rs
utils/pstor-usage/README.md
utils/pstor-usage/src/etcd.rs
utils/pstor-usage/src/main.rs
utils/pstor-usage/src/pools.rs
utils/pstor-usage/src/resources.rs
utils/pstor-usage/src/volumes.rs

refactor(pstor-usage): use client by reference
---------
fix(test): cluster tracing with a subscriber guard
Since the last tracing update we can no longer simply have a jaeger Tracer. We need to keep a
subscriber guard or alternatively set the subscriber as the global. We've opted to keep the guard
within the cluster since the test library is a library.
---------
feat(pstor-usage): modify volumes N number of times
In addition to create/delete now we also modify a volume - we publish/unpublish the volume as this
is equivalent to a user creating/deleting a pod that references a pvc.
NOTE: This is a slow operation as the nexus is created "very slowly" by mayastor.

feat(pstor-usage): take into account volume operations

---

chart/templates/core-agents-deployment.yaml
chart/templates/csi-deployment.yaml
chart/templates/jaeger-operator/jaeger.yaml
chart/templates/msp-deployment.yaml
chart/templates/operator-rbac.yaml
chart/templates/rest-deployment.yaml
chart/templates/rest-service.yaml
scripts/deploy/generate-yamls.sh

Add a namespace value which is used by the templates.
Update generate-yamls.sh to take a namespace argument. This defaults to
mayastor and is used when generating the YAML files using Helm.

chore(helm): add namespace value

---

common/src/opentelemetry.rs
control-plane/agents/core/src/core/reconciler/mod.rs
control-plane/agents/core/src/core/reconciler/poller.rs
control-plane/agents/core/src/core/scheduling/volume.rs
control-plane/agents/core/src/node/mod.rs
control-plane/agents/core/src/node/service.rs
control-plane/agents/core/src/server.rs
control-plane/agents/core/src/volume/specs.rs
control-plane/csi-controller/src/main.rs
control-plane/msp-operator/src/main.rs
control-plane/rest/service/src/main.rs
deployer/src/infra/csi.rs
deployer/src/infra/mod.rs
deployer/src/infra/rest.rs
deployer/src/lib.rs
tests/bdd/test_replicas_garbage_collection.py

On startup if the cluster had more than 5 Nodes the send event notification per node would block.
This is because the queue has only 5 elements.
Simply increasing the queue size would not necessarily improve things so instead we drop the
notification if the queue is full which is acceptable as at the moment we have no way of
"flattening" the events or to avoid running the reconcilers too often so we probably don't want
a huge queue of notifications to be built. Losing one is not a problem, just may mean we'd be a
little slower.

fix: sending node online event should not block

---

.pre-commit-config.yaml
chart/templates/csi-deployment.yaml
chart/templates/msp-deployment.yaml
deploy/core-agents-deployment.yaml
deploy/csi-deployment.yaml
deploy/jaeger-operator/deployment.yaml
deploy/jaeger-operator/jaeger.yaml
deploy/msp-deployment.yaml
deploy/rest-deployment.yaml
deploy/terraform/mod/csi-controller/main.tf
deploy/terraform/mod/k8s-operator/main.tf

chore: remove helm generation from precommit
--------------
fix: use dns name to reach rest
Using the host name creates a race as rest's node port must start ahead of its consumers.
Instead, simply use the dns name, which will be updated whenever rest is ready.
Resolves: openebs/mayastor#1076
Resolves: CAS-1288

fix: use dns name to reach rest

---

control-plane/agents/core/src/core/grpc.rs
control-plane/agents/core/src/core/reconciler/nexus/mod.rs
control-plane/agents/core/src/core/reconciler/pool/mod.rs
control-plane/agents/core/src/core/registry.rs
control-plane/agents/core/src/core/wrapper.rs
control-plane/agents/core/src/node/service.rs
control-plane/agents/core/src/pool/specs.rs
control-plane/agents/core/src/volume/specs.rs
control-plane/rest/tests/v0_test.rs

Cherry pick the node status fix from the develop branch and adds a fix for registration delays.
-----------
fix(node): node status overridden with stale status (cherry-picked)
Instead of using a copy of the node to reload, use the node itself with a grpc locked client to
update the nodes when the registry is polling mayastor.
Extra:
To clarity, in the client operations, pass the grpc client down to the update operations to that its
use is explicit rather than implicit. Added a TODO to allow us to use different timeouts for the
list operations without having to reconnect the gRPC client.
Use more getters rather than accessing fields directly
--------------
fix(node): don't stall during registration of flaky nodes
Make sure the node is alive and loaded before adding it to the configuration. …

fix(node): don't stall during (re-)registration of flaky nodes

---

common/src/store/etcd_keep_alive.rs
common/src/types/v0/message_bus/replica.rs
common/src/types/v0/store/nexus_persistence.rs
control-plane/agents/common/src/errors.rs
control-plane/agents/core/src/core/reconciler/nexus/garbage_collector.rs
control-plane/agents/core/src/core/reconciler/nexus/mod.rs
control-plane/agents/core/src/core/reconciler/pool/mod.rs
control-plane/agents/core/src/core/reconciler/volume/garbage_collector.rs
control-plane/agents/core/src/core/reconciler/volume/hot_spare.rs
control-plane/agents/core/src/core/reconciler/volume/nexus.rs
control-plane/agents/core/src/core/scheduling/resources/mod.rs
control-plane/agents/core/src/core/specs.rs
control-plane/agents/core/src/nexus/scheduling.rs
control-plane/agents/core/src/nexus/specs.rs
control-plane/agents/core/src/volume/scheduling.rs
control-plane/agents/core/src/volume/specs.rs
control-plane/agents/core/src/volume/tests.rs
tests/bdd/common/apiclient.py
tests/bdd/features/volume/nexus.feature
tests/bdd/setup.sh
tests/bdd/test_volume_nexus.py

fix: don't disown replicas from faulted volumes
Don't attempt to disown replicas if the replica volume is faulted.
Don't disown replicas if the volume target (nexus) contains the replica.
Update the replica owners on core-agent startup - we might get drop the replica nexus owners at
some point since we have obtain then from the nexus specs.
Resolves: CAS-1295
-------------
chore: don't trace reconciliation unless TRACE is set or there is work to do
For clusters with high number of volumes there are a lot of traces being sent that sometimes
seem to overwhelm the telemetry exporter.
During reconciliation we should not create spans needlessly unless we're on TRACE level or unless
the reconciler actually did work.
TODO: We need a generic strategy to cater for this
-------------
fix(nexus): …

fix: don't disown replicas from faulted volumes and recreate faulted nexuses

---

Cargo.lock
common/src/mbus_api/mod.rs
control-plane/agents/core/src/pool/service.rs
control-plane/grpc/Cargo.toml
control-plane/grpc/src/grpc_opts/mod.rs
control-plane/grpc/src/operations/pool/client.rs
control-plane/grpc/src/operations/pool/mod.rs
control-plane/grpc/src/operations/pool/server.rs
control-plane/rest/service/src/v0/mod.rs
control-plane/rest/service/src/v0/pools.rs
scripts/rust/test.sh

feat: new base grpc client that supports adding timeouts per request
This can be used as a inner helper which provides common functionality of creating a new client
connection and setting specific timeouts for each request.
This allows us to use long-lived connections with keep-alives.
-------------
refactor(pool): use of the new generic gRPC client
-------------
refactor: keep the pool gRPC server handlers cancellable
The specific service implementations will be responsible for making it otherwise. This gives finer
grained control to decide how to implement each handler.
-------------
fix: spawn core pool create/destroy to avoid early drop on timeout
The existing code does not handle being dropped very well, as it will leave things in a
potentially "bad" state.
TODO: handle serive …

feat: enable long-lived grpc clients whilst supporting per request timeouts

---

common/src/mbus_api/mod.rs
control-plane/grpc/src/grpc_opts/mod.rs

Enables http2 keep alives - this allows us to failover to servers even when a node crashes and the
core agent is recreated on another node.

fix(rest): enable http2 keep alive interval and timeout

---

Cargo.lock
deployer/src/infra/mayastor.rs

Mayastor now links against `libspdk-bundle.so`, which is located in the same
directory as binary itself (previously, it linked against libspdk.so from
a Nix package). Finding this shared library requires access to the directory
with mayastor binary from within the container. Support for that has been
added to the `composer` crate.
This fix does not affect deploying mayastor from image.
Fixes CAS-1290

fix(deployer): deploying mayastor binary is fixed

---

Cargo.lock
control-plane/agents/core/src/lib.rs
control-plane/agents/core/src/pool/service.rs
control-plane/agents/core/src/pool/tests.rs
control-plane/agents/core/src/volume/service.rs
control-plane/agents/core/src/volume/tests.rs
control-plane/grpc/Cargo.toml
control-plane/grpc/src/client.rs
control-plane/grpc/src/context.rs
control-plane/grpc/src/lib.rs
control-plane/grpc/src/operations/mod.rs
control-plane/grpc/src/operations/pool/client.rs
control-plane/grpc/src/operations/pool/mod.rs
control-plane/grpc/src/operations/pool/traits.rs
control-plane/grpc/src/operations/replica/client.rs
control-plane/grpc/src/operations/replica/traits.rs
control-plane/grpc/src/operations/volume/client.rs
control-plane/grpc/src/operations/volume/server.rs
control-plane/grpc/src/operations/volume/traits.rs
control-plane/grpc/src/tracing.rs
control-plane/rest/service/src/v0/volumes.rs
deployer/Cargo.toml
tests/tests-mayastor/src/lib.rs
utils/utils-lib/src/constants.rs

Added a tracing layer for the clients which injects tracing span context in the grpc headers.
Added a tracing layer for the servers which extracts what was injected by the client layer.
Added a new Context::spawn helper which spawns the future with the current spawn context.
Resolves: ER1-275

feat(tracing): add opentelemetry tracing to the grpc interface

---

nix/pkgs/utils/default.nix

Add kubectl-plugin build support for other CPU architectures like
arm64.
This related arm64 support: https://github.com/openebs/mayastor/issues/1063
Signed-off-by: Xinliang Liu <xinliang.liu@linaro.org>

build: add kubectl-plugin build support for arm64

---

.github/workflows/pr-commitlint.yml

When a branch is out of date with develop (no conflicts) bors fails to merge with an
"expected commitlint" error.
Not sure why that happens... we're attempting to fix that by running the commitlint on the staging.

fix(bors): attempt to fix bors failures by running lints on staging

---

common/src/types/v0/message_bus/nexus.rs
common/src/types/v0/store/definitions.rs
common/src/types/v0/store/nexus_persistence.rs
control-plane/agents/common/src/v0/msg_translation.rs
control-plane/agents/core/src/core/reconciler/volume/garbage_collector.rs
control-plane/agents/core/src/core/scheduling/nexus.rs
control-plane/agents/core/src/core/scheduling/volume.rs
control-plane/agents/core/src/nexus/registry.rs
control-plane/agents/core/src/volume/specs.rs
control-plane/agents/core/src/volume/tests.rs
tests/bdd/common/etcd.py
tests/bdd/features/pool/delete/test_feature.py
tests/bdd/features/volume/nexus-info/feature.feature
tests/bdd/features/volume/nexus-info/test_feature.py
tests/bdd/requirements.txt
utils/utils-lib/src/constants.rs

Ensure the NexusInfo structure is deleted from the persistent store when
a volume is destroyed. Also delete old NexusInfo structures when a
volume is re-published.
Also provide the ability for the control plane to pass the key that
should be use to persist the NexusInfo structure to the data plane. The
key itself has been modified to include the volume and nexus UUID.
------
Note: This PR shouldn't be merged until the corresponding data plane changes have been merged.

feat(nexus info): delete from persistent store

---

control-plane/agents/core/src/pool/specs.rs

It is possible for the pool spec to be in a "dirty" state so we should
ensure that we correctly check for this.
An issue relating to this was seen in production. It occurred when the
connection to etcd was lost in the middle of a pool creation operation.
As a consequence the pool could not subsequently be created. Manual
intervention was required to rectify this.

fix(pool spec dirty): check for pending op

---

Cargo.lock
Cargo.toml
control-plane/csi-driver/Cargo.toml
control-plane/csi-driver/build.rs
control-plane/csi-driver/node/src/main.rs
control-plane/csi-driver/node/src/nodeplugin_grpc.rs
control-plane/csi-driver/node/src/shutdown_event.rs
scripts/rust/test.sh
utils/shutdown/Cargo.toml
utils/shutdown/src/lib.rs

Upon a shutdown event (SIGINT|SIGTERM) the node plugin starts to shutdown gracefully.
New requests are rejected and current requests run till completion or until the node plugin is
killed by the kubelet.
Resolves: ER1-153
Resolves: ER1-152

feat: csi node plugin should terminate gracefully

---

common/src/types/v0/store/nexus.rs
control-plane/agents/core/src/core/reconciler/nexus/garbage_collector.rs
control-plane/agents/core/src/core/reconciler/persistent_store.rs
control-plane/agents/core/src/core/reconciler/replica/mod.rs
control-plane/agents/core/src/core/reconciler/volume/garbage_collector.rs
control-plane/agents/core/src/core/specs.rs
control-plane/agents/core/src/nexus/specs.rs
control-plane/agents/core/src/pool/registry.rs
control-plane/agents/core/src/pool/specs.rs
control-plane/agents/core/src/volume/specs.rs
control-plane/agents/core/src/volume/tests.rs

When the persistent store (etcd) is not online, we may not be able to delete resources. They remain
in the deleting state.
Mimic the volume dirty spec reconciler for other resources and simply delete them if the creation
was not successful.
Destroy resources in the deleting state from their garbage collection reconciler.
Resolves: CAS-1300

fix: delete resources pending deletion when the store is online

---

Cargo.lock
chart/templates/csi-node-daemonset.yaml
control-plane/csi-driver/Cargo.toml
control-plane/csi-driver/node/src/main.rs
deploy/csi-node-daemonset.yaml

Node plugin now retrieves hostname from node CRD via Kubernetes API
server, using kubernetes.io/hostname label.
Resolves: CAS-1095

fix(csi): use k8s api server to get node name

---

chart/templates/msp-deployment.yaml
control-plane/msp-operator/src/main.rs
deploy/core-agents-deployment.yaml
deploy/csi-controller-deployment.yaml
deploy/msp-deployment.yaml
deploy/rest-deployment.yaml

Adds a `--request-timeout` flag to the MSP operator, and sets the `default_req_timeout` Helm value (also used by core and rest) to `5s`.  The default could probably be increased.
Fixes https://github.com/openebs/mayastor/issues/1138

feat: add --request-timeout flag to MSP deployment

---

terraform/cluster/main.tf
terraform/cluster/variables.tf

Update the public ssh key variable to take the file path rather than the
content of the file. This now behaves in the same way as the private ssh
key variable.

chore(terraform): public ssh key

---

.gitignore
shell.nix
terraform/cluster/main.tf
terraform/cluster/mod/libvirt/main.tf
terraform/cluster/variables.tf
terraform/shell.nix

fix(terraform): default ssh_user to current user (if not specified)
Also, make terraform shell use the nixpkgs from the root shell.
---
chore(terraform): add network mode which defaults to NAT
Creates a named (k8snet) network which is set to autostart when the host boots up.
---
fix(rust-src): compare rust sources recursively
This is a WRITEABLE clone of the rust sources, copied from the nix output derivation.
Useful when using rust-analyzer from JetBrains which wants a writeable rust source.

Terraform - Libvirt network fixes

---

common/src/mbus_api/mod.rs
common/src/types/v0/message_bus/nexus.rs
control-plane/agents/core/src/lib.rs
control-plane/agents/core/src/nexus/mod.rs
control-plane/agents/core/src/nexus/service.rs
control-plane/agents/core/src/nexus/tests.rs
control-plane/agents/core/src/volume/tests.rs
control-plane/grpc/proto/v1/misc/common.proto
control-plane/grpc/proto/v1/nexus/nexus.proto
control-plane/grpc/src/client.rs
control-plane/grpc/src/operations/nexus/client.rs
control-plane/grpc/src/operations/nexus/mod.rs
control-plane/grpc/src/operations/nexus/server.rs
control-plane/grpc/src/operations/nexus/traits.rs
control-plane/grpc/src/operations/replica/traits.rs
control-plane/rest/service/src/v0/children.rs
control-plane/rest/service/src/v0/nexuses.rs
tests/io-engine/tests/nexus.rs

- Change transport for nexus and child ops from rest over gRPC replacing NATS.
- Fix corresponding tests

feat(replace NATS): add nexus and child ops over grpc

---

control-plane/agents/core/src/node/service.rs
tests/bdd/features/pool/reconcile/test_feature.py

fix(nodes): don't hold nodes list lock while updating 1 node
This way registrations from other nodes don't get helf up by 1 flaky node
---
fix(pytest): check against lowercase state
Otherwise we'll always think the node is not running, which is wrong.
Also, make sure the node is offline in the control-plane before restarting it.

fix(nodes): don't hold nodes list lock while updating 1 node

---

control-plane/plugin/src/bin/rest-plugin/main.rs
control-plane/plugin/src/operations.rs
control-plane/plugin/src/resources/blockdevice.rs
control-plane/plugin/src/resources/mod.rs
control-plane/plugin/src/resources/utils.rs
k8s/plugin/README.md
k8s/plugin/src/main.rs

Usage/Output All, Usable
```
➜  mayastor-control-plane (device-inv) kubectl mayastor get block-devices <node-name> --all
DEVNAME          DEVTYPE    SIZE       AVAILABLE  MODEL                       DEVPATH                                                         FSTYPE  FSUUID  MOUNTPOINT  PARTTYPE                              MAJOR            MINOR                                     DEVLINKS 
/dev/nvme0n1     disk       167772160  no         Amazon Elastic Block Store  /devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1             259     0                                                                                                                    "/dev/disk/by-path/pci-0000:00:04.0-nvme-1", "/dev/disk/by-id/nvme-nvme.1d0f-766f6c3038346136373931663365363866613164-416d617a6f6e20456 …
```

feat(kubectl plugin): add get block-devices command to list all/usable disks per node

---

common/src/types/v0/message_bus/mod.rs
common/src/types/v0/store/node.rs
control-plane/agents/common/src/errors.rs
control-plane/agents/core/src/core/registry.rs
control-plane/agents/core/src/core/scheduling/mod.rs
control-plane/agents/core/src/core/scheduling/volume.rs
control-plane/agents/core/src/nexus/specs.rs
control-plane/agents/core/src/node/mod.rs
control-plane/agents/core/src/node/service.rs
control-plane/agents/core/src/node/specs.rs
control-plane/agents/core/src/pool/specs.rs
control-plane/grpc/proto/v1/node/node.proto
control-plane/grpc/src/operations/node/client.rs
control-plane/grpc/src/operations/node/server.rs
control-plane/grpc/src/operations/node/traits.rs
control-plane/plugin/src/bin/rest-plugin/main.rs
control-plane/plugin/src/operations.rs
control-plane/plugin/src/resources/mod.rs
control-plane/plugin/src/resources/node.rs
control-plane/plugin/src/resources/utils.rs
control-plane/plugin/src/resources/volume.rs
control-plane/rest/openapi-specs/v0_api_spec.yaml
control-plane/rest/service/src/v0/nodes.rs
control-plane/rest/tests/v0_test.rs
k8s/plugin/src/main.rs
k8s/plugin/src/resources/mod.rs
tests/bdd/features/cordon/node/feature.feature

Provide the ability to cordon a node. Applying a cordon prevents the
control plane from being able to schedule resources on that node.
When cordoning a node a label must be applied. This uniquely identifies
a particular cordon operation. When uncordoning a node the appropriate
label must also be supplied.
A particular cordon label can only be applied once. Attempting to apply
a cordon with a label that already exists will fail.
Cordoning a node can be achieved through the kubectl plugin using the
following command:
kubectl-mayastor cordon node <node_id> <label>
Uncordoning a node can be achieved through the kubectl plugin using the
following command:
kubectl-mayastor uncordon node <node_id> <label>
Cordon labels can be listed through the kubectl plugin using the
following command: …

feat(cordon): allow cordoning of a node

---

common/src/types/v0/store/node.rs

The NodeSpec structure is persisted in etcd. A new member
(cordon_labels) has been added to the NodeSpec structure to support node
cordoning.
When the core agent starts, it deserialises the contents of etcd into
it's own internal data structures. During an upgrade, the core agent
will be attempting to deserialise the old NodeSpec into a new NodeSpec
structure. By marking the new field with `#[serde(default)]` we allow
this deserialisation to succeed.
The default cordon_label value will be an empty vector which is correct
as previous versions did not support cordoning. When the node is
subsequently cordoned, the new NodeSpec structure will be persisted to
etcd.
Signed-off-by: Paul Yoong <paul.yoong@mayadata.io>

fix(cordon): ensure backwards compatibility

---

control-plane/csi-driver/controller/src/client.rs
control-plane/csi-driver/controller/src/config.rs
control-plane/csi-driver/controller/src/controller.rs
control-plane/csi-driver/controller/src/identity.rs
control-plane/csi-driver/controller/src/main.rs
control-plane/csi-driver/controller/src/server.rs
control-plane/csi-driver/node/src/block_vol.rs
control-plane/csi-driver/node/src/config.rs
control-plane/csi-driver/node/src/dev.rs
control-plane/csi-driver/node/src/error.rs
control-plane/csi-driver/node/src/filesystem_vol.rs
control-plane/csi-driver/node/src/findmnt.rs
control-plane/csi-driver/node/src/identity.rs
control-plane/csi-driver/node/src/main.rs
control-plane/csi-driver/node/src/mount.rs
control-plane/csi-driver/node/src/node.rs
control-plane/csi-driver/node/src/nodeplugin_grpc.rs
control-plane/csi-driver/node/src/nodeplugin_svc.rs

- Accessibility topology will not be used for data-placement.
- Remove use of explicit topology, as it restricts usage of new node, rebuilds.
- Remove code around `local` flag
- Resolves https://github.com/openebs/mayastor/issues/1154

refactor(csi): accessible topology to be not used for data placement

---

control-plane/csi-driver/Cargo.toml
control-plane/csi-driver/node/src/main.rs
deployer/bin/src/deployer.rs
deployer/src/infra/csi_controller.rs
deployer/src/infra/csi_node.rs
deployer/src/infra/mod.rs
deployer/src/lib.rs
shell.nix
tests/bdd/common/deployer.py
tests/bdd/features/csi/controller/test_controller.py
tests/bdd/features/csi/controller/test_identity.py
tests/bdd/features/csi/node/test_csi.py
tests/bdd/features/csi/node/test_identity.py
tests/bdd/features/csi/node/test_node.py
tests/bdd/features/csi/node/test_parameters.py
utils/deployer-cluster/src/lib.rs
utils/utils-lib/src/constants.rs
utils/utils-lib/src/tracing_telemetry.rs

feat(deployer): add the csi-node plugin to the deployer
The csi-node originally came from the data-plane repo and so was never part of the deployer.
---
test(bdd): deploy the csi-node using the deployer
---
refactor: name silence log env var more appropriately
Rename quiet to silence, which seems more appropriate.

feat(deployer): add the csi-node plugin to the deployer

---

nix/pkgs/openapi-generator/default.nix
nix/pkgs/openapi-generator/source.json
scripts/rust/generate-openapi-bindings.sh

This allows us to pass custom tower clients which might be useful for building proxies, etc.
Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

chore: update to latest openapi client with custom client support
