openebs/mayastor-control-plane

nix/pkgs/control-plane/cargo-project.nix
shell.nix

Install the pre-commit hooks specified by the file and not just the message hooks.

fix(pre-commit): fix pre-commit hooks install

---

control-plane/agents/core/src/core/registry.rs

Remove 'pub' from registry start function as it is unnecessary.

chore(registry): make start function private

---

.rustfmt.toml
composer/src/lib.rs
control-plane/agents/common/src/errors.rs
control-plane/agents/common/src/lib.rs
control-plane/agents/common/src/v0/mod.rs
control-plane/agents/core/src/core/specs.rs
control-plane/agents/core/src/core/wrapper.rs
control-plane/agents/core/src/nexus/service.rs
control-plane/agents/core/src/nexus/specs.rs
control-plane/agents/core/src/node/mod.rs
control-plane/agents/core/src/node/service.rs
control-plane/agents/core/src/pool/service.rs
control-plane/agents/core/src/pool/specs.rs
control-plane/agents/core/src/volume/service.rs
control-plane/agents/core/src/volume/specs.rs
control-plane/agents/core/src/watcher/service.rs
control-plane/agents/core/src/watcher/watch.rs
control-plane/mbus-api/src/lib.rs
control-plane/mbus-api/src/message_bus/v0.rs
control-plane/mbus-api/src/receive.rs
control-plane/rest/service/src/authentication.rs
control-plane/rest/service/src/main.rs
control-plane/rest/service/src/v0/mod.rs
control-plane/rest/service/src/v0/volumes.rs
control-plane/rest/src/lib.rs
control-plane/rest/src/versions/v0.rs
control-plane/rest/tests/v0_test.rs
control-plane/store/src/etcd.rs
tests-mayastor/src/lib.rs

fix: jaeger traces for rest client test
chore: update rustfmt to use more rustfmt defaults

chore: update rustfmt to use more rustfmt defaults

---

README.md

- Use capitalisation consistent with established project style: (Mayastor not MayaStor)
- Add an experimental feature notice

docs: (readme.md)

---

common/src/mbus_api/message_bus/v0.rs
common/src/types/v0/message_bus/volume.rs
control-plane/rest/service/src/v0/volumes.rs

Allow share/unshare volume requests to be made via the message bus.

feat: add share/unshare volume to the message bus

---

Cargo.lock
Cargo.toml
common/Cargo.toml
composer/Cargo.toml
control-plane/agents/Cargo.toml
control-plane/msp-operator/Cargo.toml
control-plane/msp-operator/src/main.rs
control-plane/rest/Cargo.toml
deploy/core-agents-deployment.yaml
deploy/msp-deployment.yaml
deploy/operator-rbac.yaml
deploy/rest-deployment.yaml
deploy/rest-service.yaml
deployer/Cargo.toml
nix/pkgs/control-plane/cargo-project.nix
nix/pkgs/control-plane/default.nix
nix/pkgs/images/default.nix
rpc/Cargo.toml
scripts/release.sh
tests/tests-mayastor/Cargo.toml

This adds the MSP operator to the control plane including the
required changes to nix and deploy.

feat(msp): add k8s operator for msp resources

---

Cargo.lock
Cargo.toml
chart/templates/csi-deployment.yaml
control-plane/csi-controller/Cargo.toml
control-plane/csi-controller/src/client.rs
control-plane/csi-controller/src/controller.rs
control-plane/csi-controller/src/identity.rs
control-plane/csi-controller/src/main.rs
control-plane/csi-controller/src/server.rs
deploy/csi-deployment.yaml
nix/pkgs/control-plane/cargo-project.nix
nix/pkgs/control-plane/default.nix
nix/pkgs/images/default.nix
rpc/Cargo.toml
rpc/build.rs
rpc/src/lib.rs

This commit introduces a new CSI Controller plugin, which uses Control Plane’s new REST API
and is deployed as a separate conainerised application.
Resolves: CAS-1065

feat(csi): csi controller plugin

---

common/build.rs
common/src/types/v0/message_bus/volume.rs
control-plane/agents/core/src/core/task_poller.rs
control-plane/agents/core/src/server.rs
control-plane/agents/core/src/volume/registry.rs
control-plane/agents/core/src/volume/specs.rs
control-plane/csi-controller/src/client.rs
control-plane/csi-controller/src/controller.rs
control-plane/csi-controller/src/main.rs
control-plane/csi-controller/src/server.rs
control-plane/msp-operator/src/main.rs
control-plane/rest/openapi-specs/v0_api_spec.yaml
deploy/terraform/main.tf
deploy/terraform/mod/core/main.tf
deploy/terraform/mod/csi-controller/main.tf
deploy/terraform/mod/jaeger/crd.yaml
deploy/terraform/mod/jaeger/jaeger.yaml
deploy/terraform/mod/jaeger/main.tf
deploy/terraform/mod/jaeger/wait_deployment.sh
deploy/terraform/mod/k8s-operator/main.tf
deploy/terraform/mod/rbac/main.tf
deploy/terraform/mod/rest/main.tf
deploy/terraform/mod/sc/main.tf
deploy/terraform/simple.tfvars
deploy/terraform/variables.tf

feat(terraform): deploy jaegertracing via terraform
Deploy own Jaeger CRD because the one from the helm chart is broken.
todo: skip helm and deploy the operator directly
---
fix(csi): enable volume self healing

feat(terraform): deploy jaegertracing via terraform

---

control-plane/csi-controller/src/identity.rs

When deploying the CSI controller, it typically takes multiple restarts
before the pod is able to enter the running state. This is due to the
fact that it typically cannot communicate with the REST server
immediately.
On start up, in the event that the REST server cannot be reached return
"false" rather than an error. This communicates to the Container
Orchestrator that initialisation has not yet completed, but that the CSI
controller is otherwise healthy. This prevents the Container
Orchestrator from restarting the CSI controller (which is the case when
an error is returned).
Resolves: CAS-1148

fix(csi controller): prevent multiple restarts

---

control-plane/agents/core/src/core/wrapper.rs

When a node goes offline, its states were not immediately cleared.
Make sure we always clear the states when the node is not online by making
it implicit when we set the node status.
Prevents us from returning Pools/Nexuses as online but the returning the node as offline, which is confusing at the very least..

fix(core): clear the states when a node goes offline

---

common/src/types/v0/message_bus/replica.rs
control-plane/agents/core/src/core/reconciler/replica/mod.rs
control-plane/agents/core/src/core/reconciler/replica/tests.rs

Include a reconcile loop which removes any replica owners which no
longer exist.
Resolves: CAS-1203

feat(replica reconciler): missing replica owners

---

chart/develop/values.yaml
chart/templates/core-agents-deployment.yaml
chart/templates/csi-deployment.yaml
chart/templates/rest-deployment.yaml
chart/values.yaml
deploy/core-agents-deployment.yaml
deploy/csi-deployment.yaml
deploy/msp-deployment.yaml
deploy/rest-deployment.yaml
deploy/terraform/simple.tfvars

Add resource constraints for the control plane components. This has
been set to reasonable estimates based on a system with 109 volumes
that is handling many concurrent REST requests.
Resolves: CAS-1200

chore(control plane): add resource constraints

---

control-plane/msp-operator/src/main.rs

As part of the MSP operator implementation support was added to validate
that devices are present. This provides more feedback to the user when
using the event system from k8s.
However, when device schemas are provided in the spec, we should
normalize before comparing them to the block devices on the targeted
nodes.

feat(msp): normalize device schemas

---

control-plane/csi-controller/src/controller.rs
tests/bdd/features/csi/controller.feature
tests/bdd/test_csi_controller.py

CSI-Controller will not create volume if the storage class parameters are invalid.
Resolves - [CAS-1211](https://mayadata.atlassian.net/browse/CAS-1211)

fix(invalid sc parameters): csi-controller to not create volume on invalid sc parameters

---

Jenkinsfile
nix/pkgs/control-plane/cargo-project.nix
nix/pkgs/utils/default.nix

bonus: add printenv on the Jenkins stage

fix: adjust script path on nix file

---

tests/bdd/README.md
tests/bdd/common/apiclient.py
tests/bdd/common/deployer.py
tests/bdd/common/docker.py
tests/bdd/common/operations.py
tests/bdd/features/ana/validate/test_validate_nexus_swap.py
tests/bdd/features/csi/controller/test_feature.py
tests/bdd/features/csi/identity/test_feature.py
tests/bdd/features/garbage-collection/replicas/test_feature.py
tests/bdd/features/pool/create/disks.feature
tests/bdd/features/pool/create/name.feature
tests/bdd/features/pool/create/test_disks.py
tests/bdd/features/pool/create/test_name.py
tests/bdd/features/pool/delete/feature.feature
tests/bdd/features/pool/delete/test_feature.py
tests/bdd/features/pool/reconcile/feature.feature
tests/bdd/features/pool/reconcile/test_feature.py
tests/bdd/features/volume/observability/test_feature.py
tests/bdd/features/volume/publish/test_feature.py
tests/bdd/features/volume/replicas/test_feature.py
tests/bdd/features/volume/topology/test_feature.py
tests/bdd/features/volume/unpublish/test_feature.py

test(bdd): add pool features and tests

---

Cargo.lock
nix/pkgs/control-plane/cargo-project.nix
scripts/rust/test.sh
tests/tests-mayastor/src/lib.rs

Ensure the composer is initialised when the deployer gets built so that
the test cases can run.

fix(composer): ensure the composer is initialised

---

nix/pkgs/control-plane/cargo-project.nix

Fix up the SHA for the composer.

fix(sha): composer

---

Cargo.lock
common/Cargo.toml
composer/Cargo.toml
control-plane/agents/Cargo.toml
control-plane/csi-controller/Cargo.toml
control-plane/msp-operator/Cargo.toml
control-plane/rest/Cargo.toml
deployer/Cargo.toml
kubectl-plugin/Cargo.toml
openapi/Cargo.toml
rpc/Cargo.toml
scripts/ctrlp-cargo-test.sh
tests/tests-mayastor/Cargo.toml

It has been decided to set the version of all the crates to the same
number for the release.

chore(versions): update TOML versions

---

.github/workflows/release_artifacts.yml
Cargo.lock
common/Cargo.toml
control-plane/agents/Cargo.toml
control-plane/csi-controller/Cargo.toml
control-plane/msp-operator/Cargo.toml
control-plane/rest/Cargo.toml
deployer/Cargo.toml
kubectl-plugin/Cargo.toml
kubectl-plugin/src/main.rs
nix/lib/rust.nix
nix/pkgs/openapi-generator/source.json
nix/pkgs/utils/default.nix
openapi/Cargo.toml
rpc/Cargo.toml
tests/tests-mayastor/Cargo.toml

Merge changes pertain to the release v1.0.0

chore: merge master branch into develop

---

Cargo.lock
common/Cargo.toml
control-plane/agents/Cargo.toml
control-plane/csi-controller/Cargo.toml
control-plane/rest/Cargo.toml
tests/tests-mayastor/Cargo.toml

Unused dependencies identified using the "cargo udeps" command.

chore: remove unused dependencies

---

control-plane/agents/core/src/pool/service.rs
control-plane/grpc/src/operations/pool/client.rs
control-plane/grpc/src/operations/replica/client.rs
control-plane/grpc/src/operations/replica/server.rs
control-plane/rest/service/src/v0/replicas.rs

Follow up PR for #219 to refactor replica operations accordingly.
Signed-off-by: Abhinandan-Purkait <abhinandan.purkait@mayadata.io>

refactor(grpc): refactor replica operations

---

.gitmodules
.rustfmt.toml
Cargo.lock
Jenkinsfile
common/Cargo.toml
control-plane/agents/Cargo.toml
control-plane/rest/Cargo.toml
deployer/Cargo.toml
nix/pkgs/control-plane/cargo-project.nix
scripts/nix/git-submodule-init.sh
shell.nix
tests/tests-mayastor/Cargo.toml

chore: add mayastor-dependencies as a submodule
---
fix(jenkins): update the submodules to the committed version

chore: add mayastor-dependencies as a submodule

---

common/src/types/v0/message_bus/nexus.rs
control-plane/agents/common/src/errors.rs
control-plane/agents/core/src/volume/specs.rs
control-plane/agents/core/src/volume/tests.rs
control-plane/grpc/src/operations/volume/traits.rs
deployer/src/infra/etcd.rs

Removes iscsi support from control-plane and fixes the tests around it.

chore: remove iscsi support from control plane

---

k8s/operators/src/diskpool/main.rs

Replaces #242
References https://github.com/openebs/mayastor/issues/1089
Add a flag to disable validation of the block devices before sending the request to create the pool. This is useful in cases where image files are used, and is meant to be a temporary measure until https://github.com/openebs/mayastor/issues/1089 is dealt with appropriately.

feat: add --disable-device-validation flag

---

.github/workflows/release_artifacts.yml
k8s/plugin/src/main.rs
nix/pkgs/utils/default.nix

Closes https://github.com/openebs/mayastor-control-plane/issues/230.

Build kubectl plugin for macOS.

---

tests/bdd/features/drain/node/feature.feature

Describe the initial behaviours of the node drain feature.

test(BDD): add initial BDD for node drain

---

tests/bdd/features/cordon/node/feature.feature

Describe the initial behaviours of the node cordoning feature.

test(BDD): add inital BDD for node cordoning

---

control-plane/csi-driver/controller/src/controller.rs
control-plane/csi-driver/node/src/main.rs
control-plane/csi-driver/node/src/node.rs
tests/bdd/features/csi/controller/test_controller.py
tests/bdd/features/csi/node/test_csi.py
tests/bdd/requirements.txt

fix(csi): csi node to register node name, correct topology logic

---

k8s/plugin/README.md

Include sections related to node cordoning and update the output format
when getting the node information.
Signed-off-by: Paul Yoong <paul.yoong@mayadata.io>

docs(node cordon): update README

---

common/src/types/v0/store/volume.rs

fix(thin flag deserialize): allow deserialization of thin using default
